# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_repositories:
  - epel-release
rhbase_install_packages:
  - bash-completion
  - vim-enhanced
  - bind-utils
  - php
  - git
  - nano
  - setroubleshoot-server
  - tree
  - wget
  - docker

rhbase_start_services_vars:
  - docker
 
task:
  - name: Services | Ensure specified services are running
    service:
      name: "{{ item }}"
      enabled: true
      state: started
    with_items: "{{ rhbase_start_services_vars: }}"
    tags:
      - rhbase
      - services

