# site.yml
---

- name: Configure contol 
  roles: 
    - bertvv.rh-base
  hosts: control         
  tasks:
    - name: Installeer docker
      yum:
        name: docker
        state: latest
    - name: Installeer .NET 6.0 SDK
      yum:
        name: dotnet-sdk-6.0
        state: latest
    - name: Docker for .NET
    
 