# inventory.yml

servers:
  vars:
    ansible_user: vagrant
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    control:
      ansible_host: 192.168.56.2
      #ansible_ssh_private_key_file: ~/.vagrant/machines/control/virtualbox/private_key
      ansible_ssh_pass: vagrant
