# inventory.yml

servers:
  vars:
    ansible_user: vagrant
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    alma:
      ansible_host: 192.168.56.3
      ansible_ssh_password: vagrant
